{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "producer.fullname" . }}
  labels:
    {{- include "producer.labels" . | nindent 4 }}
spec:

  ports:
    - port: {{ .Values.service.port }}
      path: /metrics
  selector:
    {{- include "producer.selectorLabels" . | nindent 4 }}
{{- end }}