{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "producer.fullname" . }}
  labels:
    {{- include "producer.labels" . | nindent 4 }}
    release: {{ .Values.metrics.promReleaseLabel }}
spec:
  endpoints:
    - port: metrics
      path: /metrics
  selector:
    matchLabels:
    {{- include "producer.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
